branches:
  - "main"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - assets: ["target/release/*"]
  - "@semantic-release/changelog"
  - "semantic-release-cargo"
  - - "@semantic-release/git"
    - assets:
      - "CHANGELOG.md"
      - "Cargo.toml"
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
